spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/patient-registration
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#logging:
#  level:
#    org.springframework: DEBUG