spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/patient-registration
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  websocket:
    max-text-message-buffer-size: 52428800   # Corrected property name
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      uri: mongodb://localhost:27017/local
